version: '3.8'

services:
  postgres:
    container_name: corelab-pg
    image: postgres
    ports: 
      - 5431:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: corelab-bg